[package]
name = "modern-uit-thesis"
version = "0.8.0"
compiler = "0.13.0"
entrypoint = "lib.typ"
authors = ["Christian Schneiderwind <christian.schneiderwind@tu-ilmenau.de>"]
license = "MIT"
description = "TU Ilmenau Thesis Template."
repository = ""
keywords = ["thesis", "master", "uit", "bachelor", "university"]
categories = ["thesis"]
exclude = [
".git",
".gitignore",
".github",
"**/*.pdf",
]

[template]
path = "template"
entrypoint = "template.typ"
# thumbnail = "thumbnail.png"